name: Сборка и публикация XML на GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v3
        with:
          repository: physcodestyle/qa-generator
      - name: Загрузка контента
        uses: actions/checkout@v3
        with:
          path: src
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Кэширование модулей
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка модулей
        run: npm ci
      - name: Сборка XML
        run: |
          npm run build
      - name: Публикация XML
        uses: nicholasgriffintn/github-branch-deployment-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: staging
          FOLDER: dist
